export interface MenuItem {
  name: string;
  isVeg: boolean;
  price: number;
  tag?: string;
}

export interface MenuCategory {
  id: string;
  name: string;
  icon: string;
  items: MenuItem[];
  subcategories?: { name: string; items: MenuItem[] }[];
}

export const menuCategories: MenuCategory[] = [
  {
    id: "specials",
    name: "Specials",
    icon: "⭐",
    items: [
      { name: "Varhadi Chicken Handi", isVeg: false, price: 420, tag: "Chef's Pick" },
      { name: "Varhadi Mutton Handi", isVeg: false, price: 520, tag: "Chef's Pick" },
    ],
  },
  {
    id: "platters",
    name: "Platters",
    icon: "🍽️",
    items: [
      { name: "Tandoori with Platter", isVeg: false, price: 649 },
      { name: "Veg Chinese Platter", isVeg: true, price: 449 },
      { name: "Chicken Chinese Platter", isVeg: false, price: 549 },
    ],
  },
  {
    id: "sizzlers",
    name: "Sizzlers",
    icon: "🔥",
    items: [
      { name: "Veg Cheese Sizzler", isVeg: true, price: 349 },
      { name: "Paneer Tikka Sizzler", isVeg: true, price: 379 },
      { name: "Paneer Swastik Sizzler", isVeg: true, price: 399 },
      { name: "Veg Fusion Sizzler", isVeg: true, price: 369 },
      { name: "Chicken Tikka Sizzler", isVeg: false, price: 419 },
      { name: "Grilled Chicken Sizzler", isVeg: false, price: 429 },
    ],
  },
  {
    id: "soup",
    name: "Soup",
    icon: "🥣",
    items: [{ name: "Veg American Chopsuey", isVeg: true, price: 199 }],
  },
  {
    id: "starters",
    name: "Starters",
    icon: "🥗",
    subcategories: [
      {
        name: "Veg Starters",
        items: [
          { name: "Chilli Paneer", isVeg: true, price: 249 },
          { name: "Paneer Tikka", isVeg: true, price: 279 },
          { name: "Hara Bhara Kebab", isVeg: true, price: 229 },
          { name: "Paneer Dragon", isVeg: true, price: 259 },
          { name: "Corn Kebab", isVeg: true, price: 219 },
          { name: "Veg Seekh Kebab", isVeg: true, price: 239 },
          { name: "Methi Corn Kebab", isVeg: true, price: 229 },
          { name: "Paneer Achari", isVeg: true, price: 269 },
          { name: "Tandoori Stuffed Mushroom", isVeg: true, price: 259 },
          { name: "Tandoori Paneer", isVeg: true, price: 279 },
          { name: "Paneer Pahadi", isVeg: true, price: 289 },
          { name: "Paneer Malai Tikka", isVeg: true, price: 289 },
          { name: "Mushroom Tikka", isVeg: true, price: 249 },
          { name: "Kaju Paneer Stick", isVeg: true, price: 299 },
          { name: "Paneer Hilltop", isVeg: true, price: 279 },
          { name: "Chakde Paneer Tikka", isVeg: true, price: 269 },
          { name: "Veg Manchurian", isVeg: true, price: 219 },
          { name: "Veg Crispy", isVeg: true, price: 209 },
          { name: "Veg Lollipop", isVeg: true, price: 219 },
          { name: "Veg Hot Pan", isVeg: true, price: 229 },
          { name: "Paneer 65", isVeg: true, price: 249 },
          { name: "Paneer Satay", isVeg: true, price: 259 },
          { name: "Chilli Paneer Corn", isVeg: true, price: 239 },
          { name: "Chilli Paneer Hong", isVeg: true, price: 249 },
          { name: "Chilli Baby Corn", isVeg: true, price: 219 },
          { name: "Chilli Mushroom", isVeg: true, price: 229 },
          { name: "Cheese Chilli Mushroom", isVeg: true, price: 249 },
          { name: "Honey Chilli Potato", isVeg: true, price: 199 },
        ],
      },
      {
        name: "Non-Veg Starters",
        items: [
          { name: "Chilli Chicken", isVeg: false, price: 289 },
          { name: "Chilli Egg", isVeg: false, price: 179 },
          { name: "Bhatti Da Murgh", isVeg: false, price: 349 },
          { name: "Chicken Tikka", isVeg: false, price: 319 },
          { name: "Chicken Zafrani", isVeg: false, price: 329 },
          { name: "Chicken Pahadi", isVeg: false, price: 329 },
          { name: "Chicken Reshmi", isVeg: false, price: 319 },
          { name: "Chicken Afghani", isVeg: false, price: 339 },
          { name: "Chicken Malai", isVeg: false, price: 319 },
          { name: "Chicken Guddi", isVeg: false, price: 299 },
          { name: "Tandoori Chicken", isVeg: false, price: 349 },
          { name: "Chicken Seekh Kebab", isVeg: false, price: 309 },
          { name: "Chicken 65", isVeg: false, price: 279 },
          { name: "Chicken Crispy", isVeg: false, price: 279 },
          { name: "Chicken Shanghai", isVeg: false, price: 289 },
          { name: "Butter Chicken Dry", isVeg: false, price: 339 },
          { name: "Chicken Lollipop", isVeg: false, price: 299 },
          { name: "Chicken Honey Chilli", isVeg: false, price: 299 },
          { name: "Chicken Hot Pan", isVeg: false, price: 289 },
          { name: "Mutton Roast", isVeg: false, price: 399 },
        ],
      },
    ],
    items: [],
  },
  {
    id: "main-course",
    name: "Main Course",
    icon: "🍛",
    subcategories: [
      {
        name: "Veg Main Course",
        items: [
          { name: "Rajasthani Kofta", isVeg: true, price: 269 },
          { name: "Kaju Paneer Masala", isVeg: true, price: 319 },
          { name: "Veg Kadhai", isVeg: true, price: 249 },
          { name: "Veg Patiala", isVeg: true, price: 259 },
          { name: "Veg Keema Kasturi", isVeg: true, price: 269 },
          { name: "Veg Diwani Handi", isVeg: true, price: 279 },
          { name: "Veg Kebab Masala", isVeg: true, price: 269 },
          { name: "Veg Tawa", isVeg: true, price: 249 },
          { name: "Veg Lakshmi Malai", isVeg: true, price: 279 },
          { name: "Palak", isVeg: true, price: 239 },
          { name: "Methi Malai Matar Masala", isVeg: true, price: 259 },
          { name: "Paneer Masala", isVeg: true, price: 289 },
          { name: "Varhadi Paneer", isVeg: true, price: 299 },
          { name: "Paneer Pakoda Gravy", isVeg: true, price: 299 },
          { name: "Paneer Butter Masala", isVeg: true, price: 299 },
          { name: "Paneer Tikka Masala", isVeg: true, price: 319 },
          { name: "Paneer Lacchedar", isVeg: true, price: 309 },
          { name: "Paneer Patiala", isVeg: true, price: 309 },
          { name: "Paneer Angara", isVeg: true, price: 319 },
          { name: "Palak Paneer", isVeg: true, price: 289 },
          { name: "Paneer Popiya", isVeg: true, price: 309 },
          { name: "Paneer Akbari", isVeg: true, price: 319 },
          { name: "Paneer Afghani", isVeg: true, price: 329 },
          { name: "Paneer Maharaja", isVeg: true, price: 349 },
          { name: "Paneer Lababdar", isVeg: true, price: 319 },
          { name: "Paneer Lajawab", isVeg: true, price: 329 },
          { name: "Dad Special Veg", isVeg: true, price: 379, tag: "Chef Special" },
          { name: "Malai Kofta", isVeg: true, price: 279 },
          { name: "Kaju Masala", isVeg: true, price: 299 },
          { name: "Kaju Mushroom Masala", isVeg: true, price: 309 },
          { name: "Special Dal", isVeg: true, price: 199 },
          { name: "Dal Fry", isVeg: true, price: 179 },
          { name: "Dal Tadka", isVeg: true, price: 189 },
          { name: "Dal Butter", isVeg: true, price: 199 },
        ],
      },
      {
        name: "Non-Veg Main Course",
        items: [
          { name: "Egg Curry", isVeg: false, price: 189 },
          { name: "Egg Masala", isVeg: false, price: 199 },
          { name: "Chicken Roast Gravy", isVeg: false, price: 329 },
          { name: "Varhadi Chicken", isVeg: false, price: 349 },
          { name: "Chicken Masala", isVeg: false, price: 319 },
          { name: "Chicken Rogan Josh", isVeg: false, price: 339 },
          { name: "Chicken Banjara", isVeg: false, price: 329 },
          { name: "Chicken Do Pyaaza", isVeg: false, price: 319 },
          { name: "Chicken Sagwala", isVeg: false, price: 319 },
          { name: "Chicken Bhuna Masala", isVeg: false, price: 329 },
          { name: "Chicken Tikka Masala", isVeg: false, price: 349 },
          { name: "Chicken Ginger", isVeg: false, price: 319 },
          { name: "Chicken Saoji Masala", isVeg: false, price: 339 },
          { name: "Kadhai Chicken", isVeg: false, price: 329 },
          { name: "Chicken Kolhapuri", isVeg: false, price: 339 },
          { name: "Butter Chicken", isVeg: false, price: 349 },
          { name: "Boneless Butter Chicken", isVeg: false, price: 379 },
          { name: "Mutton Varhadi", isVeg: false, price: 449 },
          { name: "Mutton Masala", isVeg: false, price: 429 },
          { name: "Mutton Hyderabadi", isVeg: false, price: 449 },
          { name: "Mutton Rogan Josh", isVeg: false, price: 449 },
          { name: "Mutton Kali Mirch Masala", isVeg: false, price: 459 },
        ],
      },
    ],
    items: [],
  },
  {
    id: "breads",
    name: "Breads",
    icon: "🫓",
    items: [
      { name: "Aloo Paratha with Curd", isVeg: true, price: 129 },
      { name: "Roti", isVeg: true, price: 29 },
      { name: "Butter Roti", isVeg: true, price: 39 },
      { name: "Laccha Paratha", isVeg: true, price: 59 },
      { name: "Tawa Paratha", isVeg: true, price: 49 },
      { name: "Plain Naan", isVeg: true, price: 49 },
      { name: "Butter Naan", isVeg: true, price: 59 },
      { name: "Garlic Butter Naan", isVeg: true, price: 69 },
      { name: "Cheese Garlic Naan", isVeg: true, price: 89 },
      { name: "Kashmiri Naan", isVeg: true, price: 79 },
      { name: "Jowar Roti", isVeg: true, price: 39 },
      { name: "Bajara Roti", isVeg: true, price: 39 },
      { name: "Rumali Roti", isVeg: true, price: 49 },
      { name: "Paneer Paratha", isVeg: true, price: 119 },
      { name: "Mix Veg Paratha", isVeg: true, price: 109 },
    ],
  },
  {
    id: "rice-biryani",
    name: "Rice & Biryani",
    icon: "🍚",
    subcategories: [
      {
        name: "Rice",
        items: [
          { name: "Lemon Rice", isVeg: true, price: 149 },
          { name: "Masala Rice", isVeg: true, price: 159 },
          { name: "Garlic Rice", isVeg: true, price: 159 },
          { name: "Curd Rice", isVeg: true, price: 149 },
          { name: "Jeera Rice", isVeg: true, price: 139 },
          { name: "Veg Pulao", isVeg: true, price: 169 },
          { name: "Kashmiri Pulao", isVeg: true, price: 199 },
        ],
      },
      {
        name: "Biryani",
        items: [
          { name: "Paneer Masala Biryani", isVeg: true, price: 299 },
          { name: "Egg Biryani", isVeg: false, price: 249 },
          { name: "Chicken Dum Biryani", isVeg: false, price: 329 },
          { name: "Chicken Tikka Biryani", isVeg: false, price: 349 },
        ],
      },
    ],
    items: [],
  },
  {
    id: "fried-rice-noodles",
    name: "Fried Rice & Noodles",
    icon: "🍜",
    subcategories: [
      {
        name: "Fried Rice",
        items: [
          { name: "Veg Fried Rice", isVeg: true, price: 179 },
          { name: "Veg Schezwan Fried Rice", isVeg: true, price: 199 },
          { name: "Chicken Fried Rice", isVeg: false, price: 219 },
          { name: "Chicken Schezwan Fried Rice", isVeg: false, price: 239 },
          { name: "Egg Fried Rice", isVeg: false, price: 199 },
          { name: "Chicken Black Pepper Fried Rice", isVeg: false, price: 249 },
        ],
      },
      {
        name: "Noodles",
        items: [
          { name: "Veg Hakka Noodles", isVeg: true, price: 179 },
          { name: "Veg Schezwan Noodles", isVeg: true, price: 199 },
          { name: "Singapuri Noodles", isVeg: true, price: 209 },
          { name: "Egg Noodles", isVeg: false, price: 199 },
          { name: "Chicken Hakka Noodles", isVeg: false, price: 219 },
          { name: "Chicken Schezwan Noodles", isVeg: false, price: 239 },
        ],
      },
    ],
    items: [],
  },
  {
    id: "snacks",
    name: "Snacks",
    icon: "🥨",
    items: [
      { name: "French Fries", isVeg: true, price: 129 },
      { name: "Crispy Corn", isVeg: true, price: 149 },
      { name: "Chilli Corn", isVeg: true, price: 159 },
      { name: "Onion Pakoda", isVeg: true, price: 99 },
      { name: "Aloo Pakoda", isVeg: true, price: 99 },
      { name: "Paneer Pakoda", isVeg: true, price: 179 },
      { name: "Cheese Pakoda", isVeg: true, price: 189 },
      { name: "Veg Bullet", isVeg: true, price: 149 },
      { name: "Veg Gold Finger", isVeg: true, price: 159 },
      { name: "Masala Kulcha", isVeg: true, price: 89 },
      { name: "Cheese Garlic Kulcha", isVeg: true, price: 109 },
      { name: "Cheese Omelette", isVeg: false, price: 129 },
      { name: "Boiled Egg", isVeg: false, price: 49 },
      { name: "Egg Half Fry", isVeg: false, price: 59 },
      { name: "Egg Omelette", isVeg: false, price: 79 },
      { name: "Egg Pakoda", isVeg: false, price: 119 },
    ],
  },
];
